services:

  mysql:
    image: mysql:8.4

    container_name: opmas_mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: opmas_db

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-pchangeme"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:

    build:
      context: ./backend

    container_name: opmas_backend

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    working_dir: /var/www

    volumes:
      - ./backend:/var/www

    ports:
      - "8081:8000"

  frontend:

    build:
      context: ./frontend

    container_name: opmas_frontend

    restart: unless-stopped

    depends_on:
      - backend

    working_dir: /app

    volumes:
      - ./frontend:/app

    ports:
      - "3009:3000"

  plc-collector:

    build:
      context: ./plc-collector

    container_name: opmas_plc_collector

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    working_dir: /app

    volumes:
      - ./plc-collector:/app

volumes:

  mysql_data: